language: generic
jobs:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode11.3
      
addons:
    homebrew:
      # update: true
      packages: 
      - python3
      - cmake
before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libsndfile; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install fftw; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install libfftw3-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install libsndfile-dev; fi

# command to install dependencies
install:
  - python3 setup.py develop
# command to run tests
script:
  - python3 setup.py test
