language: generic
jobs:
  include:
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode11.3
      
addons:
    homebrew:
      # update: true
      packages: 
      - python3
      - cmake
before_install:
    - brew install libsndfile
    - brew install fftw
# command to install dependencies
install:
  - python3 setup.py develop
# command to run tests
script:
  - python3 setup.py test
