language: python
python:
  - "3.5"
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libfftw3-dev
  - sudo apt-get -y install libvorbis-dev
# command to install dependencies
install:
  - python3 setup.py develop
# command to run tests
script:
  - python3 setup.py test
