language: generic
jobs:
  include:
    - os: linux
      language: python
      python: 3.5
    - os: linux
      language: python
      python: 3.8
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode11.3
      
addons:
    apt:
      packages:
        - cmake
        - gobjc++
        - libfftw3-dev
        - libsndfile-dev
        - python3-dev
        - python3-pip
    homebrew:
      packages: 
      - python3
      - cmake
#       - libsndfile
#       - fftw
before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libsndfile; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install fftw; fi
    - sudo pip3 install Cython numpy wavefile
#     - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install libfftw3-dev; fi
#     - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install libsndfile-dev; fi

# command to install dependencies
install:
  - sudo python3 setup.py install
# command to run tests
script:
  - python3 setup.py test
