language: generic
jobs:
  include:
    - os: linux
      dist: xenial
      language: python
      python: 3.5
    - os: linux
      dist: bionic
      language: python
      python: 3.7
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode11.3
      
addons:
    apt:
      packages:
        - cmake
        - gobjc++
        - libfftw3-dev
        - libsndfile-dev       
        - python3-pip
    homebrew:
      packages: 
      - python3
      - cmake

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libsndfile; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install fftw; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install python$TRAVIS_PYTHON_VERSION-dev; fi
    - pip3 install setuptools Cython numpy wavefile

# command to install dependencies
install:
  - python3 setup.py install
# command to run tests
script:
  - python3 setup.py test
