os: osx
addons:
    homebrew:
      # update: true
      packages: 
      - python3
      - fftw
      - cmake
# command to install dependencies
install:
  - python3 setup.py develop
# command to run tests
script:
  - python3 setup.py test
