name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macOS-latest]
        python-version: ["3.6", "3.10"]

    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add requirements
      run: python -m pip install --upgrade wheel setuptools

    - name: Install dependencies
      run: |
            if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install libfftw3-dev
            elif [ "$RUNNER_OS" == "macOS" ]; then
              brew install fftw
            else
              echo "$RUNNER_OS not supported"
              exit 1
            fi

    - name: Build and install
      run: pip install --verbose .

    - name: Test
      run: python setup.py test
